"""Added a study column to course table

Revision ID: 5c2cc09f46c4
Revises: efc017143c6e
Create Date: 2025-01-26 21:15:15.831659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2cc09f46c4'
down_revision: Union[str, None] = 'efc017143c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('study', sa.String(), nullable=True))
    op.drop_index('ix_courses_id', table_name='courses')
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.create_index('ix_courses_id', 'courses', ['id'], unique=False)
    op.drop_column('courses', 'study')
    # ### end Alembic commands ###
