"""added a new study table, added relationship and made autogenerated slugify

Revision ID: aeec004d1bdd
Revises: 3fecb1504204
Create Date: 2025-01-26 22:32:25.672440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeec004d1bdd'
down_revision: Union[str, None] = '3fecb1504204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_studies_id'), 'studies', ['id'], unique=True)
    op.add_column('courses', sa.Column('study_id', sa.Integer(), nullable=True))
    op.drop_index('ix_courses_id', table_name='courses')
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_foreign_key(None, 'courses', 'studies', ['study_id'], ['id'])
    op.drop_column('courses', 'study')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('study', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.create_index('ix_courses_id', 'courses', ['id'], unique=True)
    op.drop_column('courses', 'study_id')
    op.drop_index(op.f('ix_studies_id'), table_name='studies')
    op.drop_table('studies')
    # ### end Alembic commands ###
